---
output:
  html_document:
    theme: cosmo
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.align="left", fig.width=14, fig.height=8)
```


```{r include=FALSE}
library(dplyr)
library(janitor)
library(ggplot2)
library(ggthemes)
library(stringr)
library(zoo)
library(data.table)
library(sf)
library(sp)
library(tidyr)
library(leaflet)
library(tibble)
library(htmltools)
library(leaflet.extras)

leased_not_leased_2021 <- read.csv("/Users/nycc/Downloads/Storefronts_Reported_Vacant_or_Not__Filing_Year_2020_-_2021_.csv") %>% clean_names()

# Census tract shape file
nta.shp <- st_read("/Users/nycc/Downloads/2010_nta/geo_export_f3c429f1-cc95-49e4-a3a8-51efff65c68f.shp")
nta.shp <- st_transform(nta.shp,'+proj=longlat +datum=WGS84')

vacant_nta <- leased_not_leased_2021 %>% group_by(nta, vacant_on_12_31) %>% summarize(count=n()) %>% mutate(vacant_2021=round(count/sum(count)*100,2)) %>% filter(vacant_on_12_31=="YES", nta!="") %>% left_join(nta.shp, by=c("nta"="ntacode"))

vacant_nta.shp <- vacant_nta %>% ungroup() %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84')

```


```{r}
pal = colorNumeric(
  palette = "Reds",
  domain = vacant_nta.shp$vacant_2021, 
  na.color = "Grey", 
  reverse = FALSE
)

leaflet(vacant_nta.shp, options = leafletOptions(minZoom = 10), height = 700, width =  700) %>%
  addPolygons(weight = 1,
              fillColor = ~pal(vacant_2021),
              color="black",
              stroke = TRUE,
              fillOpacity = 1) %>% 
  addLegend(position ="topleft", 
            pal=pal,
            values = vacant_nta.shp$vacant_2021,
            title = "Percent Not Leased",
            labFormat = labelFormat(suffix = "%"),
            opacity = 1) %>% setMapWidgetStyle(list(background= "white")) %>% setView(-74.01072, 40.70278, zoom = 11)
```


