---
title: "Borough_change"
output: html_document
date: "2023-08-15"
---

```{r setup, include=FALSE}
library(vroom)
ct_vacant_dataset <- vroom("https://data.cityofnewyork.us/resource/92iy-9c3n.csv?$limit=999999999") %>% clean_names()
```

```{r}
ct_vacant_dataset_yes <- ct_vacant_dataset %>% filter(vacant_on_12_31=="YES", council_district!="") %>% group_by(reporting_year, borough) %>% summarise(n_vacant = n())
# ct_vacant_dataset_yes
# head(ct_vacant_dataset)
ct_vacant_dataset_all <- ct_vacant_dataset %>% filter(council_district!="") %>% group_by(reporting_year, borough) %>% summarise(n_all = n())
ct_vacant_dataset_all <- merge(ct_vacant_dataset_yes, ct_vacant_dataset_all, by=c("reporting_year", "borough"))
```

```{r}
ct_vacant_dataset_all$pct_vacant <- round((ct_vacant_dataset_all$n_vacant/ct_vacant_dataset_all$n_all)*100,2)
ct_vacant_dataset_all$reporting_year <- recode(ct_vacant_dataset_all$reporting_year,
                                               "2019 and 2020" = 2019,  
                                               "2020 and 2021" = 2020, 
                                               "2021 and 2022" = 2021)
ct_vacant_dataset_all <- ct_vacant_dataset_all[,c("reporting_year","borough","pct_vacant")]
ct_vacant_dataset_all
```

```{r}
library(data.table) ## or library(reshape2)
# ct_vacant_dataset_all <- dcast(melt(as.data.table(ct_vacant_dataset_all), id.vars = c("borough", "reporting_year")), 
#       reporting_year + variable ~ borough, value.var = "value")[,c("reporting_year","MANHATTAN","BROOKLYN", "STATEN ISLAND", "QUEENS", "BRONX")]
ct_vacant_dataset_all
write.csv(ct_vacant_dataset_all, "../data/Vacancy_Analysis_21.csv")
```

