---
output:
  html_document:
    theme: cosmo
    df_print: paged
---

**Run 2020 version to get ct_vacant_clusters.shp_2 first.**
ct_vacant_clusters.shp_2: contains cluster information for 

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.align="left", fig.width=14, fig.height=8)
```

```{r include=FALSE}
library(dplyr)
library(janitor)
library(ggplot2)
library(ggthemes)
library(stringr)
library(zoo)
library(data.table)
library(sf)
library(tidyr)
library(leaflet)
library(tibble)
library(htmltools)
library(leaflet.extras)
library(cluster)
library(htmltools)
library(htmlwidgets)

ct.shp <- read_sf("https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_Census_Tracts_for_2020_US_Census/FeatureServer/0/query?where=1=1&outFields=*&outSR=4326&f=pgeojson")

# boro boundaries
boro <- read_sf("https://data.cityofnewyork.us/api/geospatial/tqmj-j8zm?method=export&format=GeoJSON") %>% 
  st_transform("+proj=longlat +datum=WGS84") %>% 
  st_simplify(dTolerance = .00001)
```

```{r}
leased_not_leased_2022 <- read.csv("https://data.cityofnewyork.us/resource/92iy-9c3n.csv?$limit=999999999") %>% clean_names()
```

```{r}
ct_vacant_dataset <- leased_not_leased_2022[leased_not_leased_2022$reporting_year == '2021 and 2022',]
ct_vacant_dataset$boro_ct201 <- str_extract(ct_vacant_dataset$bb, "^\\d{1}")
ct_vacant_dataset$census_tract_2 <- as.numeric(ct_vacant_dataset$census_tract) * 100
ct_vacant_dataset$census_tract_2 <-str_pad(ct_vacant_dataset$census_tract_2, width = 6, pad = "0")
ct_vacant_dataset <- transform(ct_vacant_dataset, boro_ct201 = paste0(boro_ct201, census_tract_2))
```

```{r}
ct.shp$CTLabel_round <- round(as.numeric(ct.shp$CTLabel), digits = 0)
ct.shp$CTLabel_round <- as.numeric(ct.shp$CTLabel_round)*100
ct.shp$CTLabel_round <- str_pad(ct.shp$CTLabel_round, width=6, pad="0")  
ct.shp <- transform(ct.shp,boro_ct201=paste0(BoroCode,CTLabel_round))
```

```{r}
ct.shp = ct.shp %>%
  mutate(CTLabel_round = round(as.numeric(CTLabel), digits = 0), 
         CTLabel_round = as.numeric(CTLabel_round)*100, 
         CTLabel_round = str_pad(CTLabel_round, width=6, pad="0"),
         boro_ct201 = paste0(BoroCode,CTLabel_round)) %>%
  mutate(boro_ct201 = as.character(boro_ct201)) %>%
  group_by(boro_ct201) %>% 
  summarize(geometry = st_union(geometry))
```

```{r}
# ---- Anne's suggestion:
# In the chunk starting row 55 we're dropping the decimal in order to be able to merge with the storefront data - which only provides the round numbers for the locations. It's BANANAS to me that they provide the data that way, by removing the decimals they are deciding to use old census tract designations, but only for tracts where there has been enough growth to merit them being divided. Frankly it makes no sense that they did that, but given that we're trying to make it work, I've at least condensed our spatial file. Previously we were merging each storefront to all tracts that it could match (ie if the storefront is reported to be in CT 2, we would merge it with both CT 2.01 and CT 2.02) now I've combined the shapes so that there will only be one existing shape labelled 2. We could use the lat lon to find the correct 2020 tract but there are some missing obs. The spatial difference is less bad than I had thought it might be - places where you see a red line are where I've combined the two (or more) tracts.

# ^ The 2020 map doesn't implement this to try to best preserve the original map in the replication.

# aggregate the vacancy data by modified census tract and combine with spatial data
ct_vacant <- ct_vacant_dataset %>% 
  group_by(boro_ct201, vacant_on_12_31) %>%
  summarize(count_vacant = n()) %>%
  complete(vacant_on_12_31, fill = list(count_vacant = 0)) %>%
  mutate(
    perc_vacant = count_vacant / sum(count_vacant),
    perc_vacant = round(perc_vacant, 2)) %>%
  ungroup() %>%
  as.data.frame() %>%
  left_join(ct.shp, by = c("boro_ct201"))
```

```{r}
# prep spatial data for plotting
ct_vacant.shp <- ct_vacant %>% 
  filter(vacant_on_12_31=="YES") %>% 
  ungroup() %>% 
  st_as_sf() %>% 
  st_transform('+proj=longlat +datum=WGS84')
```

```{r}
ct_vacant_clusters <- ct_vacant_dataset %>%
  group_by(boro_ct201, vacant_on_12_31) %>%
  summarize(count_vacant=n()) %>%
  complete(vacant_on_12_31, fill = list(count_vacant = 0)) %>%
  mutate(perc_vacant = count_vacant/sum(count_vacant),
         perc_vacant = round(perc_vacant, 2),
         total_storefronts = sum(count_vacant))
ct_vacant_clusters <- ct_vacant_clusters[-c(1:2),] %>%
  filter(vacant_on_12_31=="YES")
```

```{r}
set.seed(124)
wss <- sapply(1:10, function(k){kmeans(ct_vacant_clusters[,4:5], k, nstart = 50, iter.max = 15)$tot.withinss})
plot(1:10, wss,type="b", xlab= "k values")

km <- kmeans(ct_vacant_clusters[,c(4:5)], centers = 3)
km

#vacancy$cluster = km$cluster
ct_vacant_clusters$cluster <- km$cluster

table(ct_vacant_clusters$cluster)
table(ct_vacant_clusters$cluster_recoded)

ct_vacant_clusters <- ct_vacant_clusters %>% mutate(cluster_recoded=ifelse(cluster==1,1,ifelse(cluster==2,3,2)))

ct_vacant_clusters.shp <- ct_vacant_clusters %>% left_join(ct.shp %>% mutate(boro_ct201=as.character(boro_ct201)), by = c("boro_ct201")) %>% ungroup() %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84')
```

```{r include=FALSE}
ct_vacant_clusters_no_zero <- ct_vacant_clusters %>% filter(perc_vacant!=0)

set.seed(125)
wss <- sapply(1:10, function(k){kmeans(ct_vacant_clusters_no_zero[,4:5], k, nstart = 50, iter.max = 15)$tot.withinss})
plot(1:10, wss,type="b", xlab= "k values")
#abline(v=4)

km <- kmeans(ct_vacant_clusters_no_zero[,c(4:5)], centers = 2)
km
```

```{r}
#vacancy$cluster = km$cluster
ct_vacant_clusters$cluster <- 0

ct_vacant_clusters_no_zero$cluster <- km$cluster

ct_vacant_clusters <- ct_vacant_clusters %>% filter(perc_vacant==0) %>% bind_rows(ct_vacant_clusters_no_zero)
```

```{r}
ct_vacant_clusters.shp <- ct_vacant_clusters %>% 
  left_join(ct_vacant_clusters.shp, by = c("boro_ct201", "cluster_recoded")) %>%
  ungroup() %>% 
  st_as_sf() %>% 
  st_transform('+proj=longlat +datum=WGS84')
```


```{r, include=FALSE}
cluster_map <- leaflet(ct_vacant_clusters.shp , options = leafletOptions(minZoom = 10), height = 700, width =  700) %>%
  addPolygons(data=boro, stroke = T, fill=F, color = "#666666", weight = 1) %>%
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==1), weight = 1,
              fillColor = "red",
              color="black",
              stroke = TRUE,
              fillOpacity = 0.8) %>%
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==2) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 ,
              fillColor = "pink",
              color="black",
              stroke = TRUE,
              fillOpacity = 0.8) %>%
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==3) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 ,
              fillColor = "orange",
              color="black",
              stroke = TRUE,
              fillOpacity = 0.6) %>% addPolygons(data = ct.shp %>% mutate(boro_ct201=as.character(boro_ct201)) %>% anti_join(ct_vacant.shp %>% data.frame(), by=c("boro_ct201")), weight = 1,
              fillColor = "white",
              color="black",
              stroke = TRUE,
              fillOpacity = 1) %>% addLegend(position ="topleft", 
            colors = c("red", "orange", "pink"),
            labels = c("vacant: 14.41% storefronts: 206", "vacant: 10.37%  storefronts: 84", "vacant: 13.86% storefronts: 24"),
            title = "Cluster Means",
            opacity = 8) %>% 
  setMapWidgetStyle(list(background= "white")) %>%
    setView(-73.94000, 40.73309, 10.5) 
```

```{r}
km <- kmeans(ct_vacant_clusters[,c(4:5)], centers = 3)
km
```

```{r}
# saving map
saveWidget(cluster_map, file=file.path('../visuals', 
                               "cluster_map_2022.html"))
mapshot(cluster_map, file = "../visuals/cluster_map_2022.png")
```

```{r}
ct_vacant_clusters.shp_2
```

```{r}
cluster_map <- leaflet(ct_vacant_clusters.shp , options = leafletOptions(minZoom = 10), height = 700, width =  700) %>%
  addPolygons(data=boro, stroke = T, fill=F, color = "#666666", weight = 1) %>%
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==1), weight = 1,
              fillColor = "red",
              color="black",
              stroke = TRUE,
              fillOpacity = 0.8) %>%
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==2) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 ,
              fillColor = "pink",
              color="black",
              stroke = TRUE,
              fillOpacity = 0.8) %>%
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==3) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 ,
              fillColor = "orange",
              color="black",
              stroke = TRUE,
              fillOpacity = 0.6) %>% addPolygons(data = ct.shp %>% mutate(boro_ct201=as.character(boro_ct201)) %>% anti_join(ct_vacant.shp %>% data.frame(), by=c("boro_ct201")), weight = 1,
              fillColor = "white",
              color="black",
              stroke = TRUE,
              fillOpacity = 1) %>% addLegend(position ="topleft", 
            colors = c("red", "orange", "pink"),
            labels = c("vacant: 14.41% storefronts: 206", "vacant: 10.37%  storefronts: 84", "vacant: 13.86% storefronts: 24"),
            title = "Cluster Means",
            opacity = 8) %>% 
  setMapWidgetStyle(list(background= "white")) %>%
    setView(-73.94000, 40.73309, 10.5) 
```

```{r}
# 2020 map
# leaflet(ct_vacant_clusters.shp_2 , options = leafletOptions(minZoom = 10), height = 700, width =  700) %>%
#   addPolygons(data=boro, stroke = T, fill=F, color = "#666666", weight = 1) %>%
#   addPolygons(data = ct_vacant_clusters.shp_2 %>% filter(cluster_recoded==1), weight = 1,
#               fillColor = "orange",
#               color="black",
#               stroke = TRUE,
#               fillOpacity = 0.8) %>%
#   addPolygons(data = ct_vacant_clusters.shp_2 %>% filter(cluster_recoded==2) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 ,
#               fillColor = "pink",
#               color="black",
#               stroke = TRUE,
#               fillOpacity = 0.8) %>%
#   addPolygons(data = ct_vacant_clusters.shp_2 %>% filter(cluster_recoded==3) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 ,
#               fillColor = "red",
#               color="black",
#               stroke = TRUE,
#               fillOpacity = 0.6) %>% addPolygons(data = ct.shp %>% mutate(boro_ct201=as.character(boro_ct201)) %>% anti_join(ct_vacant.shp %>% data.frame(), by=c("boro_ct201")), weight = 1,
#               fillColor = "white",
#               color="black",
#               stroke = TRUE,
#               fillOpacity = 1) %>% addLegend(position ="topleft", 
#             colors = c("red", "orange", "pink"),
#             labels = c("vacant: 15% storefronts: 221", "vacant: 11%  storefronts: 77", "vacant: 9% storefronts: 26"),
#             title = "Cluster Means",
#             opacity = 8) %>% 
#   setMapWidgetStyle(list(background= "white")) %>%
#     setView(-73.94000, 40.73309, 10.5) 
```


```{r}
merged_map <- leaflet(options = leafletOptions(minZoom = 10), height = 700, width =  700) %>%
  addPolygons(data=boro, stroke = T, fill=F, color = "#666666", weight = 1) %>%
  
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==1), 
              group = "2021",
              weight = 1,
              fillColor = "red",
              color="black",
              stroke = TRUE,
              fillOpacity = .8) %>%
  addPolygons(data = ct_vacant_clusters.shp_2 %>% filter(cluster_recoded==1), weight = 1, 
              group = "2020",
              fillColor = "orange",
              color="black",
              stroke = TRUE,
              fillOpacity = .8) %>%
  
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==2) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 , 
              group = "2021",
              fillColor = "pink",
              color="black",
              stroke = TRUE,
              fillOpacity = .8) %>%
  addPolygons(data = ct_vacant_clusters.shp_2 %>% filter(cluster_recoded==2) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 , 
              group = "2020",
              fillColor = "pink",
              color="black",
              stroke = TRUE,
              fillOpacity = .8) %>%
  
  addPolygons(data = ct_vacant_clusters.shp %>% filter(cluster_recoded==3) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 , 
              group = "2021",
              fillColor = "orange",
              color="black",
              stroke = TRUE,
              fillOpacity = .8) %>% 
  addPolygons(data = ct_vacant_clusters.shp_2 %>% filter(cluster_recoded==3) %>% st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84'), weight = 1 , 
              group = "2020",
              fillColor = "red",
              color="black",
              stroke = TRUE,
              fillOpacity = 8) %>%
  
  addPolygons(data = ct.shp %>% mutate(boro_ct201=as.character(boro_ct201)) %>% 
                anti_join(ct_vacant.shp %>% data.frame(), by=c("boro_ct201")), group = "2021", weight = 1,
              fillColor = "white",
              color="black",
              stroke = TRUE,
              fillOpacity = 1) %>% addLegend(position ="topleft", 
            colors = c("red", "orange", "pink"),
            labels = c("vacant: 14.41% storefronts: 206", "vacant: 10.37%  storefronts: 84", "vacant: 13.86% storefronts: 24"),
            title = "Cluster Means: 2021",
            opacity = 8) %>% 
  
  addPolygons(data = ct.shp %>% mutate(boro_ct201=as.character(boro_ct201)) %>% 
                anti_join(ct_vacant.shp %>% data.frame(), by=c("boro_ct201")), group = "2020", weight = 1,
              fillColor = "white",
              color="black",
              stroke = TRUE,
              fillOpacity = 1) %>% addLegend(position ="topleft", 
            colors = c("red", "orange", "pink"),
            labels = c("vacant: 15.24% storefronts: 221", "vacant: 10.94%  storefronts: 89", "vacant: 13.72% storefronts: 27"),
            title = "Cluster Means: 2020",
            opacity = 8) %>% 
  
  addLayersControl(
    baseGroups = c("2020", "2021"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  setMapWidgetStyle(list(background= "white")) %>%
    setView(-73.94000, 40.73309, 10.5) 
```

```{r}
# saving map
saveWidget(merged_map, file=file.path('../visuals', 
                               "cluster_map_2022.html"))
mapshot(merged_map, file = "../visuals/cluster_map_2022.png")
```

