---
output:
  html_document:
    theme: cosmo
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.align="left", fig.width=14, fig.height=8)
```

```{r include=FALSE}
library(dplyr)
library(janitor)
library(ggplot2)
library(ggthemes)
library(stringr)
library(zoo)
library(data.table)
library(sf)
library(sp)
library(tidyr)
library(leaflet)
library(tibble)
library(htmltools)
library(leaflet.extras)
library(RSocrata)

leased_not_leased_2022 <- read.csv("https://data.cityofnewyork.us/resource/92iy-9c3n.csv?$limit=999999999") %>% clean_names()
```

```{r}
library(councildown)
council_districts = unzip_sf("https://www.nyc.gov/assets/planning/download/zip/data-maps/open-data/nycc_21d.zip") %>% 
	st_read() %>% 
	st_transform(st_crs(4326))
```

```{r}
# ---- OLD CODE ----
# # Census tract shape file
# cd.shp <- st_read("/Users/nycc/Downloads/City\ Council\ Districts/geo_export_5ab108fe-1723-40b1-ba2a-255cb4deb4a3.shp")
# cd.shp <- st_transform(cd.shp,'+proj=longlat +datum=WGS84')
```

```{r}
# boro boundaries
boro <- read_sf("https://data.cityofnewyork.us/api/geospatial/tqmj-j8zm?method=export&format=GeoJSON") %>% 
  st_transform("+proj=longlat +datum=WGS84") %>% 
  st_simplify(dTolerance = .00001)
```


```{r}
head(leased_not_leased_2022)
```


```{r}
vacant_cd <- leased_not_leased_2022[leased_not_leased_2022$reporting_year == '2021 and 2022',] %>% 
  group_by(council_district, vacant_on_12_31) %>% 
  summarize(count=n()) %>%
  mutate(vacant_2022=round(count/sum(count)*100,2)) %>%
  filter(vacant_on_12_31=="YES", council_district!="") %>% 
  left_join(council_districts, by = c("council_district"="CounDist"))
```

```{r}
vacant_cd.shp <- vacant_cd %>% 
  ungroup() %>% 
  st_as_sf() %>% 
  st_transform('+proj=longlat +datum=WGS84')
```


```{r}

int_cd <- classInt::classIntervals(vacant_cd.shp$vacant_2022, n = 5, style = 'sd')

# ---- OLD CODE ----
# pal_cd <- colorBin(
#   palette = c("#800000","#a44736","#c37b6c","#ddafa7","#e5cccc"),
#   bins = int_nta$brks,
#   domain = vacant_cd.shp$vacant_2021, 
#   na.color = "#E6E6E6",
#   reverse = TRUE
# )

pal_cd = leaflet::colorBin( # issues with councildown's colorBin
  palette = c("#800000","#a44736","#c37b6c","#ddafa7","#e5cccc"),
  bins= int_cd$brks,
  domain = vacant_cd.shp$vacant_2022, 
  na.color = "White", 
  reverse = TRUE
)
```

```{r}
m <- leaflet(vacant_cd.shp) %>%
  addCouncilStyle(add_dists = TRUE, dist_year = "2013") %>%
#  addPolygons(data=boro, stroke = T, fill=F, color = "#666666", weight = 1) %>%
  addPolygons(data=vacant_cd.shp, weight = 1,
              fillColor = ~pal_cd(vacant_2022),
              color="Black",
              stroke = TRUE,
              fillOpacity = .7,
              popup = paste("Council District: ", vacant_cd.shp$council_district, "</br>","Number Vacant: ", vacant_cd.shp$count, "</br>", "Percent Vacant: ", paste(vacant_cd.shp$vacant_2022,"%", sep=""))) %>% 
  addLegend(position ="topleft", 
            pal=pal_cd,
            values = vacant_cd.shp$vacant_2022,
            title = "Percent Vacant",
            labFormat = labelFormat(suffix = "%", digits = 1),
            opacity = 1) 

library(htmlwidgets)
saveWidget(m, file=file.path('../visuals', 
                               "vacant_cd_2022.html"))
mapshot(m, file = "../visuals/vacant_cd_2022.html.png")
```


