---
output:
  html_document:
    theme: cosmo
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.align="left", fig.width=14, fig.height=8)
```


```{r include=FALSE}
library(dplyr)
library(janitor)
library(ggplot2)
library(ggthemes)
library(stringr)
library(zoo)
library(data.table)
library(sf)
library(sp)
library(tidyr)
library(leaflet)
library(tibble)
library(htmltools)
library(leaflet.extras)
library(RSocrata)
library(htmlwidgets)
#
# read all files below via api, dont have the files locally
leased_not_leased_2021 <- fread("https://data.cityofnewyork.us/resource/92iy-9c3n.csv?$limit=999999999") %>% clean_names()

# subset to 2021 and 2022
leased_not_leased_2021 <- leased_not_leased_2021[reporting_year %in% "2021 and 2022", ]
leased_not_leased_2021[, bbl := as.character(bbl)]

# Census tract shape file
nta.shp <- st_read("https://data.cityofnewyork.us/api/geospatial/cpf4-rkhq?method=export&format=GeoJSON") %>%  st_transform('+proj=longlat +datum=WGS84')

# boro boundaries
boro <- read_sf("https://data.cityofnewyork.us/api/geospatial/tqmj-j8zm?method=export&format=GeoJSON") %>% 
  st_transform("+proj=longlat +datum=WGS84") %>% 
  st_simplify(dTolerance = .00001)

vacant_nta <- leased_not_leased_2021 %>% 
  group_by(nta, vacant_on_12_31) %>% 
  summarize(count=n()) %>%
  mutate(vacant_2021=round(count/sum(count)*100,2)) %>%
  filter(vacant_on_12_31=="YES", nta!="") %>% 
  left_join(nta.shp, by=c("nta"="ntacode"))

vacant_nta.shp <- vacant_nta %>% 
  ungroup() %>% 
  st_as_sf() %>% 
  st_transform('+proj=longlat +datum=WGS84') %>% 
  #remove park cemeteries
  filter(grepl("park-cemet*", ntaname)==F)

leased_not_leased_2021 %>% filter(borough_1=="QUEENS")

```


```{r}
# check appropriate binning for the map
# https://gistbok.ucgis.org/bok-topics/statistical-mapping-enumeration-normalization-classification#Classification
plot(density(vacant_nta.shp$vacant_2021))
# data is quite normal with some tail
# using sd for the map classification

# pal = colorNumeric(
#   palette = "Reds",
#   domain = vacant_nta.shp$vacant_2021, 
#   na.color = "#E6E6E6", 
#   reverse = FALSE
# )
#
#
int_nta <- classInt::classIntervals(vacant_nta.shp$vacant_2021, n = 5, style = 'sd')

pal_nta <- colorBin(
  palette = c("#800000","#a44736","#c37b6c","#ddafa7","#e5cccc"),
  bins = int_nta$brks,
  domain = vacant_nta.shp$vacant_2021, 
  na.color = "#E6E6E6",
  reverse = TRUE
)

m <- leaflet(vacant_nta.shp, 
        options = leafletOptions(minZoom = 10), height = 700, width =  700
        ) %>%
  addPolygons(data=boro, stroke = T, fill=F, color = "#666666", weight = 1) %>%
  addPolygons(weight = 0.7,
              fillColor = ~pal_nta(vacant_2021),
              color="Black",
              stroke = TRUE,
              fillOpacity = 1,
              popup = paste("NTA Name: ", paste(vacant_nta.shp$ntaname, " (", vacant_nta.shp$nta,")",sep=""), "</br>", "Number Vacant: ", vacant_nta.shp$count, "</br>" ,"Percent Vacant: ", paste(vacant_nta.shp$vacant_2021,"%", sep=""))) %>% 
  addLegend(position ="topleft", 
            pal=pal_nta,
            values = vacant_nta.shp$vacant_2021,
            title = "Percent Vacant",
            labFormat = labelFormat(suffix = "%", digits = 1),
            opacity = 1) %>% 
  setMapWidgetStyle(list(background= "white")) %>%
    setView(-73.94000, 40.73309, 10.5) 


mapview::mapshot(m, file = "visuals/Storefronts_nta_map.png", 
        vwidth = 900, vheight = 870)

saveWidget(m, file="visuals/Storefronts_nta_map_21_22.html")
```


