---
output:
  html_document:
    theme: cosmo
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())

```

```{r}
source("code/00_load_dependencies.R")
```

```{r include=FALSE}

vacant_nta <- vacant_dataset %>% 
  group_by(nta, vacant_on_12_31) %>% 
  summarize(count=n()) %>% 
  mutate(vacant_2021=round(count/sum(count)*100, 2)) %>%
  filter(vacant_on_12_31=="YES", nta != "") %>% 
  ungroup() %>% as.data.frame() %>%
  left_join(nta.shp, by = c("nta"="ntacode"), keep = T) %>%
  st_as_sf()

vacant_nta.shp <- vacant_nta %>% 
  ungroup() %>% 
  st_as_sf() %>% 
  st_transform('+proj=longlat +datum=WGS84') %>% 
  #remove park cemeteries
  filter(grepl("park-cemet*", ntaname)==F)
```


```{r}
# check appropriate binning for the map
# https://gistbok.ucgis.org/bok-topics/statistical-mapping-enumeration-normalization-classification#Classification
plot(density(vacant_nta.shp$vacant_2021))
# data is quite normal with some tail
# using sd for the map classification

# pal = colorNumeric(
#   palette = "Reds",
#   domain = vacant_nta.shp$vacant_2021, 
#   na.color = "#E6E6E6", 
#   reverse = FALSE
# )
#
#
int_nta <- classInt::classIntervals(vacant_nta.shp$vacant_2021, n = 4, style = 'sd')

pal_nta <- leaflet::colorBin(
  #palette = c("#800000","#a44736","#c37b6c","#ddafa7","#e5cccc"),
  palette = pal_nycc("warm"),
  bins = int_nta$brks,
  domain = vacant_nta.shp$vacant_2021, 
  na.color = "#E6E6E6",
  #reverse = TRUE
)
```

```{r}
# m <- leaflet(vacant_nta.shp, 
#         options = leafletOptions(minZoom = 10)) %>%
#   addCouncilStyle() %>% 

m <- leaflet() %>% 
  addCouncilStyle() %>% 
  addPolygons(data=boro.shp, stroke = T, fill=F, color = "#666666", weight = 1) %>%
  addPolygons(data=vacant_nta.shp,
    weight = 0.7,
              fillColor = ~pal_nta(vacant_2021),
              color="Black",
              stroke = TRUE,
              fillOpacity = 1,
              popup = paste("NTA Name: ", paste(vacant_nta.shp$ntaname, " (", vacant_nta.shp$nta,")",sep=""), "</br>", "Number Vacant: ", vacant_nta.shp$count, "</br>" ,"Percent Vacant: ", paste(vacant_nta.shp$vacant_2021,"%", sep=""))) %>% 
  addLegend_decreasing(position ="topleft", decreasing = T,
            pal=pal_nta,
            values = vacant_nta.shp$vacant_2021,
            title = "Percent Vacant",
            labFormat = labelFormat(suffix = "%", digits = 1),
            opacity = 1)  
  # setMapWidgetStyle(list(background= "white")) %>%
  #   setView(-73.94000, 40.73309, 10.5) 


# mapview::mapshot(m, file = "visuals/Storefronts_nta_map.png", 
#         vwidth = 900, vheight = 870)

mapshot(m, file = "visuals/Storefronts_nta_map.png")
         
saveWidget(m, file="visuals/Storefronts_nta_map_21_22.html")
```

### NTA - highest and lowest vacancies 
```{r}
nta_tops <- leased_not_leased_2021 %>% 
  group_by(nta, vacant_on_12_31) %>% 
  summarize(count=n()) %>%
  mutate(vacant_2021=round(count/sum(count)*100,2))
setDT(nta_tops)
nta_tops[order(count, decreasing = FALSE)][1:6]
vpct <- dcast(nta_tops, nta + count ~ vacant_on_12_31, value.var = "vacant_2021")
vpct[order(NO, decreasing = TRUE)]
# vacant on 12/31
top_no_vac <- vpct[order(NO, decreasing = TRUE)][1:5][, .(nta)]
top_vac <- vpct[order(YES, decreasing = TRUE)][1:6][, .(nta)]
# get names
leased_not_leased_2021[nta %in% top_no_vac$nta, unique(nbhd), nta]
leased_not_leased_2021[nta %in% top_vac$nta, unique(nbhd), nta]
```

```{r}
round(vpct[vpct$nta %in% c("QN19", "MN19", "QN03", "MN25", "BK23") & !is.na(vpct$YES) ,]$YES,1)
```


### NTA - highest and lowest vacancies - Anne version
```{r}
# 
# nta_tops <- leased_not_leased_2021 %>% 
#   group_by(nta, vacant_on_12_31) %>% 
#   summarize(count=n()) %>%
#   mutate(vacant_2021=round(count/sum(count)*100,2))
# 
# setDT(nta_tops)
# 
# nta_tops_wide = nta_tops %>%
#   pivot_wider(names_from = vacant_on_12_31, 
#               values_from = c(count, vacant_2021)) %>%
#   replace_na(list(count_YES = 0, vacant_2021_YES = 0))
#   
# # 6 NTAs with the lowest vacancies (by %)
# nta_tops_wide %>% 
#   filter(!grepl("99", nta)) %>%
#   arrange(vacant_2021_YES) %>%
#   head(5) %>%
#   left_join(leased_not_leased_2021 %>%
#               select(nta, nbhd) %>%
#               unique(), join_by(nta == nta)) %>%
#   select(nta, nbhd, count_YES, vacant_2021_YES)
# # 6 NTAs with the highest vacancies (by %)
# nta_tops_wide %>% 
#   filter(!grepl("99", nta)) %>%
#   arrange(desc(vacant_2021_YES)) %>%
#   head(5) %>%
#   left_join(leased_not_leased_2021 %>%
#               select(nta, nbhd) %>%
#               unique(), join_by(nta == nta)) %>%
#   select(nta, nbhd, count_YES, vacant_2021_YES)

```

